source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WBBDKNofityHUD_Example', :exclusive => true do
  pod "WBBDKNofityHUD", :path => "../"
end

target 'WBBDKNofityHUD_Tests', :exclusive => true do
  pod "WBBDKNofityHUD", :path => "../"

  
end
